services:
  db:
    image: postgres:16
    restart: always
    container_name: blockscout-db
    environment:
      POSTGRES_PASSWORD: blockscout_db_pass
      POSTGRES_USER: blockscout
      POSTGRES_DB: blockscout
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: always
    container_name: blockscout-redis

  backend:
    image: blockscout/blockscout:latest
    restart: always
    container_name: blockscout-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://blockscout:blockscout_db_pass@db:5432/blockscout
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_HTTP_URL: http://64.52.80.204:8545
      ETHEREUM_JSONRPC_WS_URL: ws://64.52.80.204:8546
      ETHEREUM_JSONRPC_TRACE_URL: http://64.52.80.204:8545
      CHAIN_ID: '9999'
      NETWORK: BLOCK
      SUBNETWORK: BLOCK Mainnet
      COIN: BLOCK
      COIN_NAME: BLOCK
      LOGO: /images/blockscout_logo.svg
      SUPPORTED_CHAINS: '[]'
      BLOCK_TRANSFORMER: clique
      ECTO_USE_SSL: 'false'
      SECRET_KEY_BASE: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5rLVq7t5rGnKmjwR0
      PORT: '4000'
      POOL_SIZE: '80'
      POOL_SIZE_API: '10'
      INDEXER_MEMORY_LIMIT: 4g
      FETCH_REWARDS_WAY: trace
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: '50'
      INDEXER_CATCHUP_BLOCKS_CONCURRENCY: '5'
      FIRST_BLOCK: '0'
      LAST_BLOCK: ''
      TRACE_FIRST_BLOCK: '0'
      SHOW_TXS_CHART: 'true'
      ENABLE_TXS_STATS: 'true'
      SHOW_PRICE_CHART: 'false'
      DISABLE_EXCHANGE_RATES: 'true'
      DISABLE_KNOWN_TOKENS: 'true'
      API_V2_ENABLED: 'true'
      MIX_ENV: prod
      CACHE_BLOCK_COUNT_PERIOD: '7200'
      CACHE_TXS_COUNT_PERIOD: '7200'
      CACHE_ADDRESS_COUNT_PERIOD: '7200'
      CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: '1800'
      CACHE_ADDRESS_SUM_PERIOD: '3600'
      ACCOUNT_ENABLED: 'false'
      DISABLE_BRIDGE_MARKET_CAP_UPDATER: 'true'
      APPS_MENU: 'false'
      COIN_BALANCE_ON_DEMAND_FETCHER_BATCH_SIZE: '10'
      TOKEN_BALANCE_ON_DEMAND_FETCHER_BATCH_SIZE: '10'
      ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: '600'
    ports:
      - "4000:4000"
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"

  frontend:
    image: ghcr.io/blockscout/frontend:latest
    restart: always
    container_name: blockscout-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_HOST: 64.111.92.74
      NEXT_PUBLIC_API_PORT: '80'
      NEXT_PUBLIC_API_PROTOCOL: http
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
      NEXT_PUBLIC_NETWORK_NAME: BLOCK
      NEXT_PUBLIC_NETWORK_SHORT_NAME: BLOCK
      NEXT_PUBLIC_NETWORK_ID: '9999'
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: BLOCK
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: BLOCK
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: '18'
      NEXT_PUBLIC_HOMEPAGE_CHARTS: "['daily_txs']"
      NEXT_PUBLIC_IS_TESTNET: 'false'
      NEXT_PUBLIC_NETWORK_RPC_URL: http://64.52.80.204:8545
      NEXT_PUBLIC_APP_HOST: 64.111.92.74
      NEXT_PUBLIC_APP_PROTOCOL: http
      NEXT_PUBLIC_API_BASE_PATH: /
      NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ''
      NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE: validation
      NEXT_PUBLIC_MARKETPLACE_ENABLED: 'false'
      NEXT_PUBLIC_HAS_BEACON_CHAIN: 'false'
      NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED: 'false'
      NEXT_PUBLIC_FOOTER_LINKS: '[{"title":"Community","links":[{"text":"Telegram","url":"https://t.me/bl0ck_official"},{"text":"Twitter / X","url":"https://x.com/bl0ck_gg"},{"text":"TikTok","url":"https://www.tiktok.com/@bl0ck_official"}]}]'
      NEXT_PUBLIC_NETWORK_EXPLORERS: "[]"
      NEXT_PUBLIC_HOMEPAGE_PLATE_TEXT_COLOR: rgb(255,255,255)
      NEXT_PUBLIC_HOMEPAGE_PLATE_BACKGROUND: rgb(30,30,30)
    ports:
      - "3000:3000"

volumes:
  postgres-data:
